//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportingSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати фото.
        /// </summary>
        public static string addPhoto {
            get {
                return ResourceManager.GetString("addPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтвердити.
        /// </summary>
        public static string buttonConfirm {
            get {
                return ResourceManager.GetString("buttonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати.
        /// </summary>
        public static string buttonEdit {
            get {
                return ResourceManager.GetString("buttonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скинути.
        /// </summary>
        public static string buttonReset {
            get {
                return ResourceManager.GetString("buttonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінити фото.
        /// </summary>
        public static string changePhoto {
            get {
                return ResourceManager.GetString("changePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архів дій з компаніями.
        /// </summary>
        public static string companyArchive {
            get {
                return ResourceManager.GetString("companyArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість компаній.
        /// </summary>
        public static string companyCount {
            get {
                return ResourceManager.GetString("companyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПІБ директора.
        /// </summary>
        public static string companyDataDirectorName {
            get {
                return ResourceManager.GetString("companyDataDirectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість співробітників.
        /// </summary>
        public static string companyEmployees {
            get {
                return ResourceManager.GetString("companyEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не додано жодної компанії.
        /// </summary>
        public static string companyEmpty {
            get {
                return ResourceManager.GetString("companyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата завершення ліцензії ----------.
        /// </summary>
        public static string companyLicense {
            get {
                return ResourceManager.GetString("companyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розробник не може додавати компанії.
        /// </summary>
        public static string companyWarning {
            get {
                return ResourceManager.GetString("companyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити фото.
        /// </summary>
        public static string deletePhoto {
            get {
                return ResourceManager.GetString("deletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число компаній.
        /// </summary>
        public static string directorInfoAmountCompanies {
            get {
                return ResourceManager.GetString("directorInfoAmountCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загальне число співробітників в компаніях.
        /// </summary>
        public static string directorInfoAmountEmployees {
            get {
                return ResourceManager.GetString("directorInfoAmountEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата завершення ліцензії.
        /// </summary>
        public static string directorInfoStatusLicense {
            get {
                return ResourceManager.GetString("directorInfoStatusLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип поточної ліцензії.
        /// </summary>
        public static string directorInfoTypeLicense {
            get {
                return ResourceManager.GetString("directorInfoTypeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компанії.
        /// </summary>
        public static string headerCompanies {
            get {
                return ResourceManager.GetString("headerCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакти.
        /// </summary>
        public static string headerContacts {
            get {
                return ResourceManager.GetString("headerContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Співробітники.
        /// </summary>
        public static string headerEmployments {
            get {
                return ResourceManager.GetString("headerEmployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мова.
        /// </summary>
        public static string headerLanguage {
            get {
                return ResourceManager.GetString("headerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звітна система для бізнесу.
        /// </summary>
        public static string headerNameSystem {
            get {
                return ResourceManager.GetString("headerNameSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проекти.
        /// </summary>
        public static string headerProgects {
            get {
                return ResourceManager.GetString("headerProgects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Етапи.
        /// </summary>
        public static string headerSteps {
            get {
                return ResourceManager.GetString("headerSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] personalUserInfo19Photo {
            get {
                object obj = ResourceManager.GetObject("personalUserInfo19Photo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса проживання.
        /// </summary>
        public static string personalUserInfoAddressFact {
            get {
                return ResourceManager.GetString("personalUserInfoAddressFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса реєстрації.
        /// </summary>
        public static string personalUserInfoAddressReg {
            get {
                return ResourceManager.GetString("personalUserInfoAddressReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Премія поточна.
        /// </summary>
        public static string personalUserInfoAddSalary {
            get {
                return ResourceManager.GetString("personalUserInfoAddSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відрядження.
        /// </summary>
        public static string personalUserInfoAssignment {
            get {
                return ResourceManager.GetString("personalUserInfoAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата народження.
        /// </summary>
        public static string personalUserInfoBirthDate {
            get {
                return ResourceManager.GetString("personalUserInfoBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Днів в системі.
        /// </summary>
        public static string personalUserInfoDaysInSystem {
            get {
                return ResourceManager.GetString("personalUserInfoDaysInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email особистий.
        /// </summary>
        public static string personalUserInfoEmailSelf {
            get {
                return ResourceManager.GetString("personalUserInfoEmailSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email робочий.
        /// </summary>
        public static string personalUserInfoEmailWork {
            get {
                return ResourceManager.GetString("personalUserInfoEmailWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прізвище.
        /// </summary>
        public static string personalUserInfoFirstName {
            get {
                return ResourceManager.GetString("personalUserInfoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відпустка.
        /// </summary>
        public static string personalUserInfoHoliday {
            get {
                return ResourceManager.GetString("personalUserInfoHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лікарняні.
        /// </summary>
        public static string personalUserInfoHospital {
            get {
                return ResourceManager.GetString("personalUserInfoHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Особистий кабінет.
        /// </summary>
        public static string personalUserInfoNamePage {
            get {
                return ResourceManager.GetString("personalUserInfoNamePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон особистий.
        /// </summary>
        public static string personalUserInfoPhoneSelf {
            get {
                return ResourceManager.GetString("personalUserInfoPhoneSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон робочий.
        /// </summary>
        public static string personalUserInfoPhoneWork {
            get {
                return ResourceManager.GetString("personalUserInfoPhoneWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посада.
        /// </summary>
        public static string personalUserInfoPosition {
            get {
                return ResourceManager.GetString("personalUserInfoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оклад поточний.
        /// </summary>
        public static string personalUserInfoSalary {
            get {
                return ResourceManager.GetString("personalUserInfoSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я.
        /// </summary>
        public static string personalUserInfoSecondName {
            get {
                return ResourceManager.GetString("personalUserInfoSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ІПН.
        /// </summary>
        public static string personalUserInfoTaxNumber {
            get {
                return ResourceManager.GetString("personalUserInfoTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По-Батькові.
        /// </summary>
        public static string personalUserInfoThirdName {
            get {
                return ResourceManager.GetString("personalUserInfoThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на адміністратора.
        /// </summary>
        public static string personalUserInfoUserRolAdm {
            get {
                return ResourceManager.GetString("personalUserInfoUserRolAdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на адміністратора.
        /// </summary>
        public static string personalUserInfoUserRolCusAdm {
            get {
                return ResourceManager.GetString("personalUserInfoUserRolCusAdm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на директора.
        /// </summary>
        public static string personalUserInfoUserRolCusDir {
            get {
                return ResourceManager.GetString("personalUserInfoUserRolCusDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на керівника.
        /// </summary>
        public static string personalUserInfoUserRolCusMan {
            get {
                return ResourceManager.GetString("personalUserInfoUserRolCusMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на працівника.
        /// </summary>
        public static string personalUserInfoUserRolCusWorker {
            get {
                return ResourceManager.GetString("personalUserInfoUserRolCusWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на розробника.
        /// </summary>
        public static string personalUserInfoUserRolDev {
            get {
                return ResourceManager.GetString("personalUserInfoUserRolDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата прийняття на роботу.
        /// </summary>
        public static string personalUserInfoWorkStartDate {
            get {
                return ResourceManager.GetString("personalUserInfoWorkStartDate", resourceCulture);
            }
        }
    }
}
